import uvicorn
from config import settings
from fastapi import FastAPI, Depends
from datetime import datetime
from pydantic import BaseModel, Field, field_validator
from opensearchpy import AsyncOpenSearch


async def get_db_client():
    client = AsyncOpenSearch(
        hosts=[{"host": settings.opensearch_host, "port": settings.opensearch_port}],
        http_auth=(settings.opensearch_user, settings.opensearch_password),
    )
    try:
        yield client
    finally:
        await client.close()


app = FastAPI()


class VlmPayload(BaseModel):
    model_name: str = Field(..., description="Name of the used model")
    caption: str = Field(..., description="Text generated by VLM")
    embedding: list[float]

    @field_validator("embedding")
    @classmethod
    def validate_embedding_dim(cls, v):
        if len(v) != 384:
            raise ValueError(f"embedding must have 384 dimensions, got {len(v)}")
        return v


class UavTelemetry(BaseModel):
    drone_id: str = Field(..., description="UAV's identification number")
    timestamp: datetime = Field(..., description="Capture time")
    location: list[float] = Field(
        ..., description="Location latitude and longitude of the drone"
    )
    altitude: float = Field(..., description="Altitude of the drone")

    @field_validator("location")
    @classmethod
    def validate_location(cls, v):
        if len(v) < 2:
            raise ValueError(
                "location must be a list with at least 2 elements [lat, lon]"
            )
        return v


class UavFlightDataPayload(BaseModel):
    model_data: VlmPayload
    metrics: UavTelemetry


@app.post("/api/ingest")
async def receive_flight_data(
    payload: UavFlightDataPayload, client: AsyncOpenSearch = Depends(get_db_client)
) -> dict[str, str]:
    body = {
        "@timestamp": payload.metrics.timestamp.isoformat(),
        "sovva": {
            "uav": {
                "drone_id": payload.metrics.drone_id,
                "telemetry": {
                    "location": {
                        "lat": payload.metrics.location[0],
                        "lon": payload.metrics.location[1],
                    },
                    "altitude_m": payload.metrics.altitude,
                },
            },
            "vlm": {
                "model_type": payload.model_data.model_name,
                "caption": payload.model_data.caption,
                "embedding": payload.model_data.embedding,
            },
        },
    }
    try:
        response = await client.index(
            index="sovva", body=body, id=payload.metrics.drone_id
        )
        return {"message": f"Data reached database. Index {response["result"]}"}
    except Exception as e:
        print(f" Indexing error: {e}")
        return {"error": f"Failed to ingest data: {str(e)}"}


if __name__ == "__main__":
    uvicorn.run(app, host="127.0.0.1", port=settings.api_port)
