from pydantic import BaseModel, Field
from typing import List
from datetime import datetime


class TelemetryData(BaseModel):
    drone_id: str = Field(..., description="UAV's identification number")
    timestamp: datetime = Field(..., description="Capture time")
    location: list[float] = Field(
        ..., description="Location latitude and longitude of the drone"
    )
    altitude: float = Field(..., description="Altitude of the drone")


class SovvaPayload(BaseModel):
    model_name: str = Field(..., description="Name of the used model")
    caption: str = Field(..., description="Text generated by VLM")
    embedding: List[float] = Field(..., min_length=384, max_length=384)
    frame_timestamps: List[float] = Field(..., description="List of frames timestamps in [s]")


class UavFlightDataPayload(BaseModel):
    model_data: SovvaPayload
    metrics: TelemetryData
